# Generated by Django 3.0.6 on 2020-06-09 09:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
